# Generated by Django 4.2.7 on 2024-10-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(verbose_name='Сумма платежа')),
                ('status', models.CharField(choices=[('не оплачен', 'Не оплачен'), ('оплачен', 'Оплачен')], max_length=100, verbose_name='Статус заказа')),
                ('payment_type', models.CharField(choices=[('наличные', 'Наличные'), ('карта', 'Карта')], max_length=100, verbose_name='Тип оплаты')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
