# Generated by Django 4.2.7 on 2024-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('не оплачен', 'Не оплачен'), ('оплачен', 'Оплачен')], max_length=100, verbose_name='Статус платежа'),
        ),
    ]
