# Generated by Django 4.2.7 on 2024-10-09 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('создан', 'Создан'), ('подтвержден', 'Подтвержден')], max_length=100, verbose_name='Статус заказа')),
                ('time_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('time_of_conformation', models.DateTimeField(default=None, verbose_name='Время подтверждения')),
            ],
        ),
    ]
