# Generated by Django 4.2.7 on 2024-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_conformation',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время подтверждения'),
        ),
    ]
