# Generated by Django 4.2.7 on 2024-10-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_order_id'),
        ('orders', '0002_alter_order_options_alter_order_time_of_conformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
